### ISSUE TITLE
No more CI on PRs

### ISSUE THREAD

**Issue by xhochy** [mbr/simplekv#111]
It looks like no CI is running anymore on PRs. Does this need a Travis reactivation maybe?

cc @fmarczin @crepererum

**Comment by criemen** [comment]
Travis-CI.org is shutting down, see https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D.
The new pricing can be found here: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
Alternatively, there is also documentation of how to port jobs from travis CI to Github Actions: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by xhochy** [comment]
Closing this as we have solved that over https://github.com/data-engineering-collective/minimalkv.
