### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by fmarczin** [mbr/simplekv#113]
Hi @mbr !

Since there are a couple of open PRs, and I no longer have the capacity to reliably review and release, there is a growing list of great contributions that don't get merged.

This has created a situation where a fork becomes more likely. To avoid that and distribute reviewing and releasing on more shoulders, I suggest adding a couple of contributors as maintainers, namely @xhochy, @fjetter, @jochen-ott-by and @peter-hoffmann-by. We could also change ownership to each one of them if you prefer. 
 
I can vet all of them. They are either former or current colleagues of mine with contributions to simplekv.

What do you think? I'm not sure how you are using simplekv these days and how much you still want to be involved. Would love to hear your thoughts. 

Cheers, Felix

**Comment by criemen** [comment]
I guess this is a good time as any to announce that I'm stepping down as simplekv maintainer.
I'm currently working in static source code analysis, not data science, and my current employer doesn't use simplekv.

From my time at Blue Yondre, I can also vet for all 4 maintainers Felix proposes, and think that the project is in good hands with them.

**Comment by fmarczin** [comment]
Thanks @criemen for updating us 👍 

@mbr: Any chance to look into this and make that change? I'm in a similar position as Cornelius.

**Comment by xhochy** [comment]
As there was no progress on this and we want to finally work again with releases, we forked the project over at https://github.com/data-engineering-collective/minimalkv.

**Comment by hoffmann** [comment]
Additional maintainers have been added
