### ISSUE TITLE
Push a new release

### ISSUE THREAD

**Issue by asteinlein** [mbr/simplekv#21]
Could you please push a new release to PyPI? Version 0.9.2 breaks on Python 3, which seems to have been fixed after that release.

**Comment by mbr** [comment]
Sorry about the (admittedly quite long) delay, but can you elaborate a bit on that? I can't see any breakage on the 0.9.2 release commit on travis, which also tests against Python3. If something breaks for you there, I'd be good to know because it isn't caught by the tests.
