### ISSUE TITLE
Docs or Python3 implementation is wrong (not sure which)

### ISSUE THREAD

**Issue by jonathanq** [mbr/simplekv#22]
The API states that a `get(key)` will return a string (http://pythonhosted.org/simplekv/#simplekv.KeyValueStore.get)

However the python3 section makes an ambiguous statement about all values as bytes in Python 3 (http://pythonhosted.org/simplekv/#python-3).

I understand that bytes is what is stored in the underlying stores for Py3.  However, based on the published API - it should be decoding that back to a string when it returns it to the caller.

I am not sure what your intention was with Python3 support.  So either the docs need to be updated to make it clear that the return value of a `get(key)` in Python3 is bytes.  Or the code needs to be updated to decode the result when it returns it.

I am using an upstream project (https://github.com/mbr/flask-kvsession/) which assumes the return value is a string and fails in Python3 as a result.

**Comment by asielen** [comment]
I am having the same issue. get() returns bytes object which then fails to unpickle. 

Did you figure out a workaround?

**Comment by jonathanq** [comment]
We subclassed the RedisStore class and overrode the _get(key) method to decode the key from bytes to str(). 

```
class CustomRedisStore(RedisStore):
    def _get(self, key):
        return super()._get(key).decode('utf-8')
```

If you are using DictStore (in memory memory) - you will need to do the _get and the _put
```
class MemoryStore(DictStore):
    def _put(self, key, data):
        return self._put_file(key, BytesIO(data.encode('utf-8')))

    def _get(self, key):
        return super(MemoryStore, self)._get(key).decode('utf-8')
```

**Comment by mbr** [comment]
Bytes should be the type returned, I think it's even checked in the tests. The docs are incorrect, because they were written before Python 3 was a thing (in my mind).
