### ISSUE TITLE
setup.py should mention Python 3 support

### ISSUE THREAD

**Issue by giampaolo** [mbr/simplekv#24]
This is helpful for CLI tools like "caniusepython3". I erroneously thought simplekv didn't have python 3 support because of that. 
Fixing this is easy. In setup.py:

        classifiers=[
            'Programming Language :: Python :: 2',
            'Programming Language :: Python :: 3',
        ],

**Comment by mbr** [comment]
Finally fixed in ec45eb5. Also, [unleash](https://github.com/mbr/unleash) checks for it now.
