### ISSUE TITLE
How to use memcache with simplekv?

### ISSUE THREAD

**Issue by li-gjhawar** [mbr/simplekv#27]
I am trying to use memcache with simplekv, But as mentioned in the documentation, I get an IO error when I  try to clear the cache.

from simplekv.memory.memcachestore import MemcacheStore
import memcache
import redis
import datetime
# store = RedisStore(redis.StrictRedis())

store = MemcacheStore(memcache.Client(['127.0.0.1:11211'], debug = 0))
store.ttl_support = True
app = create_app(**name**)
current_kvsession = KVSessionExtension(store, app)
for key in app.kvsession_store.keys():
        logger.debug(key)
        m = current_kvsession.key_regex.match(key)
        logger.debug('found %s', m)
        logger.debug(app.kvsession_store.delete(key))

Since memcache doesn`t support  app.kvsession_store.keys(). Do I need to remember the key somewhere so that I won`t have to pull it out of memcache? Let me know if more explaination is needed.

**Comment by fmarczin** [comment]
@li-gjhawar Are you still doing this? If so, please note #44.

**Comment by fmarczin** [comment]
@li-gjhawar If you have no objections, I would close this issue, since the memcached backend likely will no longer be supported.
