### ISSUE TITLE
PrefixDecorator fails with non-prefixed keys

### ISSUE THREAD

**Issue by fmarczin** [mbr/simplekv#28]
If the "parent" store of a PrefixDecorator contains non-prefixed keys, the prefixed store fails when it sees those keys, e.g. when listing keys.

Example:

    s1 = FilesystemStore('./store')
    s2 = PrefixDecorator('pre-', s1)
    s1.put('foo', 'val')
    s2.put('bar', 'val')
    print(s1.keys())  # -> outputs ['foo', 'pre-bar']
    print(s2.keys())  # expected: ['bar'], but fails with AssertionError

This is not completely trivial to fix, since KeyTransformingDecorator currently doesn't expect the transformation to change the number of keys, which I think is the expected behaviour here (s2.keys() only returning the one key).

I have a fix for both issues ready, so it would be great to know if you think you can use that.

**Comment by mbr** [comment]
That is indeed worth fixing and woudl be appreciated. Twice so, if it came with tests =).

**Comment by mbr** [comment]
Should be fixed in current master.
