### ISSUE TITLE
simplekv doesn't come up in search on pypi

### ISSUE THREAD

**Issue by fmarczin** [mbr/simplekv#29]
No idea if this is technically an issue in simplekv, but I though it's worth reporting:

While simplekv is on pypi (https://pypi.python.org/pypi/simplekv/0.9.3), and it does appear in the list of packages (https://pypi.python.org/pypi?%3Aaction=index), the package is not listed when I search for "simplekv" , "key value storage" or "key-value". Weirdly, a search for "simplekv" does return two hits: Flask-KVSession and legitfs, which both mention simplekv in their README.

**Comment by fmarczin** [comment]
Possibly related to this issue in pypi: https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when

**Comment by mbr** [comment]
Apparently, including the name in the description does not fix it either? I've (for now) updated the description on PyPI (at the cost of a direct download link for the release, PyPI-installs still work though).
