### ISSUE TITLE
Allow "/" in keys

### ISSUE THREAD

**Issue by fmarczin** [mbr/simplekv#31]
I was wondering what your opinion is on allowing / in keys.

The rationale behind it is that most if not all backends allow it, and some backends like S3 ([AWS docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html)) and file systems handle this in a way that makes the keyspace much more organized.

I would see this purely as a change in some backends, and it's not supposed to affect the API semantics to make it in any way (pseudo-)hierarchical.

If you think this has merit, I would come up with a PR.

**Comment by mbr** [comment]
It's explicitly forbidden, to avoid confusion/security issues/clashes. ``/`` is basically the initial reason for having key names this restricted. Maybe simplekv will become hierarchical in the distant future, but I think that might even run afoul the "simple" part =).
