### ISSUE TITLE
Table already defined on this metadata instance

### ISSUE THREAD

**Issue by avilaton** [mbr/simplekv#33]
I am using kvsession in a flask app and it works as expected. I ran into this while running tests:
```
Traceback (most recent call last):
  File "/home/user/project/tests/base.py", line 20, in setUpClass
    cls.app = get_app('testing')
  File "/home/user/project/__init__.py", line 30, in get_app
    session_store = SQLAlchemyStore(engine, db.Model.metadata, 'kvsession')
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/simplekv/db/sql.py", line 21, in __init__
    Column('value', LargeBinary, nullable=False)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 398, in __new__
    "existing Table object." % key)
InvalidRequestError: Table 'kvsession' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```
It somehow happens because the tests call the initialization twice. I could not work around this, any ideas?

**Comment by mbr** [comment]
Which test framework are you using? It should be possible to avoid calling the initialization twice - could you come up with a minimal test case?

**Comment by avilaton** [comment]
It is a client's project in which tests are being run with plain old unittest. I will try to cook up a clean example.

**Comment by mbr** [comment]
May I suggest having a look at py.test? =)

**Comment by avilaton** [comment]
I have a branch in which I am moving things over to py.test which is almost ready, but we needed this now and I thought I could ask for your feedback on how sane it would be to add `extend_existing=True` to the Table creation. I'll get back to you on that py.test, thanks!

**Comment by mbr** [comment]
I can't give a lot of feedback on that now at the moment, I would have to
dig in deeper than I have time for at this moment. However, if you're doing
initialization twice and want a workaround for that committed, my answer
would be "fix your initialization" =)

**Comment by avilaton** [comment]
Done, moved to pytest, works perfectly.
