### ISSUE TITLE
Blue Yonder simplekv development effort

### ISSUE THREAD

**Issue by Corni** [mbr/simplekv#43]
Hi,
we at Blue Yonder use simplekv a lot.
We love that it is easily possible to use a filesystem-backed store during development and replace that by using a S3-backed store for production, and maybe adding, without hassle, a redis cache in front of the data store. And all without touching the application code!
To further our relationship with simplekv, we’d love to help out with the development and put effort into making simplekv even better.

We want to work on the following things:
- Merging the open pull requests from @fmarczin and @Corni
- Developing a high-quality Azure Blob Storage backend. We know that the code in the current pull request is not on par quality-wise with the existing code base, so we will work on that.
Allowing slashes and spaces in key names. We have several applications where this is unfortunately unavoidable, as well as full support for all backends in our patch.
- Discuss dropping the memcache backend - a backend which does not support like half the operations, can’t fake them either and just raises exceptions instead is in my opinion not useful.
- We currently have code internally which takes an ini file or an URL and turns that into a simplekv store instance. We would like to either open source that project by itself, or, preferably, include the code in simplekv.

If we are on the same page with these goals, we would love if you could consider granting @fmarczin and maybe me commit access to the project.
We remain committed to the idea that a simple, basic API which does not everything and which does not expose or emulate hierarchical structures is a great fit for many projects.

Regards,
Cornelius

**Comment by mbr** [comment]
Since you live pretty much next door, I'll be contacting you directly soon. I think it's time to share some of the development responsibility. =)

**Comment by mbr** [comment]
Alright, it's done. Commit responsibly =).

You may want to consider an AUTHORs file, or augment the README to show that this project now has multiple core contributors.

**Comment by Corni** [comment]
Thanks a lot for the trust! We will add an AUTHOR file soon(ish) ;-)
