### ISSUE TITLE
PyPi package is outdated

### ISSUE THREAD

**Issue by csu** [mbr/simplekv#55]
The PyPi package looks outdated. When I try using it with Python 3, it fails because the `BotoStore.py` file still tries to use `from itertools import imap` instead of using `_compat`.

**Comment by mbr** [comment]
@csu That is my fault, because I have not uploaded the new version yet. I'm sorry.

**Comment by csu** [comment]
No problem! Just thought I'd let you know the PyPi version is a bit behind. Running it off the git repo works perfectly.

**Comment by Corni** [comment]
There is now a new release, 0.11.0 on github, but not yet on PyPi.
