### ISSUE TITLE
AzureException always raised as KeyError

### ISSUE THREAD

**Issue by mmoeddel** [mbr/simplekv#62]
Hi,
when trying to put a file to an azure blob storage

`store.put_file('myfile.txt','myfile.txt')`

this confusing KeyError was returned:
`  File "...lib/python2.7/site-packages/simplekv/__init__.py", line 177, in put_file
    return self._put_filename(key, file)
  File "...lib/python2.7/site-packages/simplekv/net/azurestore.py", line 123, in _put_filename
    return key
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "...lib/python2.7/site-packages/simplekv/net/azurestore.py", line 38, in map_azure_exceptions
    raise KeyError(key)
KeyError: 'myfile.txt' `

In this case the cause was a missing internet connecting. Could you please consider to improve the exception handling and not raise all AzureException as KeyError.

**Comment by fmarczin** [comment]
It looks like in this case the exception handling suppresses important information. I will try to come up with a patch.
