### ISSUE TITLE
Add new Databases (CouchDB)

### ISSUE THREAD

**Issue by SvenAkk** [mbr/simplekv#92]
Hi, is it possible for users to add new databases?
I really  like the project but would like to be able to extend it with other databases, such as CouchDB or Rakis, on the fly.
Is this possible, and if so, how?

**Comment by xhochy** [comment]
@SvenAkk Have a look at the implementation for MongoDB https://github.com/mbr/simplekv/blob/master/simplekv/db/mongo.py This should be a good guidance on what you need to support CouchDB.

**Comment by fmarczin** [comment]
@SvenAkk : Are you still working on this?

**Comment by SvenAkk** [comment]
Not at the moment no.
